### ISSUE TITLE
Builds for Mac OS broken

### ISSUE THREAD

**Issue by cmahnke** [sass/dart-sass-embedded#115]
The release `tgz` for Linux x86 only contains one big executable, where the binaries for OS X are jus stubs, needing access to the `src` directory. This is quite inconvenient in terms of (cross platform) scripting and litters `/usr/local/bin` (or any other installation directory).

Please provide a uniform file layout across platforms (which would be just one big executable without dependencies to `src`). Or don't advertise archives as binary packages, if they really aren't.

One might use a tool like [`makeself`](https://makeself.io/) to emulate such a behaviour.

**Comment by ntkme** [comment]
See https://github.com/google/dart_cli_pkg/issues/67

**Comment by ntkme** [comment]
> This is quite inconvenient in terms of (cross platform) scripting and litters `/usr/local/bin` (or any other installation directory).

You can unpack into `/opt/sass_embedded` and then symlink `/opt/sass_embedded/dart-sass-embedded` into `/usr/local/bin` which works cross platform.

> Or don't advertise archives as binary packages, if they really aren't.

Remember dart is a vm language. The linux binary is basically architecture-specific aot-snapshot embedded into a dart vm runtime executable. The mac release just has the aot-snapshot and vm executable as separate files so that the vm executable from dart sdk is already code signed. To create a single file like linux, it would require code signing on the single file, which is not yet supported in dart_cli_pkg.

**Comment by nex3** [comment]
Closing this out because the builds aren't actually broken, this is just a request for a different layout—which, as @ntkme says, is blocked on having code signing support in `dart_cli_pkg`.
