### ISSUE TITLE
why not support older versions of glibc?

### ISSUE THREAD

**Issue by f1-outsourcing** [sass/dart-sass-embedded#123]
For upgrading projects, would be nice to have support for older versions.

```
[]# ./dart-sass-embedded
./dart-sass-embedded: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./dart-sass-embedded)
./dart-sass-embedded: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by ./dart-sass-embedded)
./dart-sass-embedded: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./dart-sass-embedded)
```

**Comment by ntkme** [comment]
Since you are upgrading your projects, why don't upgrade your environment first? If there is any reason that you must use an over ten-year-old glibc, you can try compile the [Dart SDK](https://github.com/dart-lang/sdk) locally against the old glibc and then compile this package yourself. - As dart is a VM language, the support of any libc is a question of on the VM side, not on the app side.
